using '../main.bicep'

param location = readEnvironmentVariable('AZURE_LOCATION')
param containerImage = readEnvironmentVariable('CONTAINER_IMAGE')
param containerAppName = readEnvironmentVariable('CONTAINER_APP_NAME')
param revisionSuffix = readEnvironmentVariable('REVISION_SUFFIX')
param containerRegistryServer = readEnvironmentVariable('CONTAINER_REGISTRY_SERVER')
param containerRegistryResourceId = readEnvironmentVariable('CONTAINER_REGISTRY_RESOURCE_ID')
param postgresAdminPassword = readEnvironmentVariable('POSTGRES_ADMIN_PASSWORD')
param myMobileNumber = readEnvironmentVariable('MY_MOBILE_NUMBER')
param acsSourcePhoneNumber = readEnvironmentVariable('ACS_SOURCE_PHONE_NUMBER')
param entraTenantId = readEnvironmentVariable('ENTRA_TENANT_ID')
param entraClientId = readEnvironmentVariable('ENTRA_CLIENT_ID')
param entraClientSecret = readEnvironmentVariable('ENTRA_CLIENT_SECRET')
param authorizedAgentAppIds = readEnvironmentVariable('AUTHORIZED_AGENT_APP_IDS')
param existingAcsResourceId = readEnvironmentVariable('EXISTING_ACS_RESOURCE_ID')
param acsCallbackAudience = readEnvironmentVariable('ACS_CALLBACK_AUDIENCE')
param acsCallbackUrl = readEnvironmentVariable('ACS_CALLBACK_URL')
param mcpAllowedHosts = readEnvironmentVariable('MCP_ALLOWED_HOSTS')
